-- E2,E3,E4,E5

-- E2
-- a.
WITH OCTOMBRIE AS (
    SELECT 
        TO_DATE('2024-10-01', 'YYYY-MM-DD') + LEVEL - 1 AS ZI
    FROM DUAL
    CONNECT BY LEVEL <= 31
)
SELECT
    TO_DATE(OCT.ZI),
    COUNT(R.BOOK_DATE)
FROM OCTOMBRIE OCT
LEFT JOIN RENTAL_LBC R ON EXTRACT(DAY FROM OCT.ZI) = EXTRACT(DAY FROM R.BOOK_DATE) 
    AND EXTRACT(MONTH FROM BOOK_DATE) = 10
GROUP BY OCT.ZI 
ORDER BY OCT.ZI;


-- b. 
CREATE TABLE OCTOMBRIE_AO(
    ID INT PRIMARY KEY,
    DATA DATE NOT NULL
);

CREATE SEQUENCE SECV_OCTOMBRIE_AO
START WITH 1
INCREMENT BY 1;

INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-03', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-07', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-12', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-15', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-19', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-21', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-23', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-25', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-28', 'YYYY-MM-DD'));
INSERT INTO OCTOMBRIE_AO (ID, DATA) VALUES (SECV_OCTOMBRIE_AO.NEXTVAL, TO_DATE('2024-10-30', 'YYYY-MM-DD'));

COMMIT;







